LabEsUFPA/meuEgresso

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/duvidas-e-sugestões.md, .github/ISSUE_TEMPLATE/feature-request.md
Foi adicionado exemplos concretos de tarefas a serem realizadas.
Removido o checkbox ao apontar a origem da solicitação.
=> docs: atualizado modelo de Feature Request

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/config/security/SecurityConfig.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/grupo/GrupoController.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoPublicDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioPublicDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/AnuncioModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/ComentarioModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/ContribuicaoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/CursoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/DepoimentoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoColocaoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoColocaoModelId.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoEmpresaModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoEmpresaModelId.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EmpresaModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EnderecoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EtniaModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/FaixaSalarialModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/GeneroModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/GrupoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/PesquisaCientificaModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/SexoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/TipoBolsaModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/TitulacaoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/TrabalhoPublicadoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/UsuarioModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/audit/Auditable.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/mongo/FatorRiscoMongo.example, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/mongo/QuestionarioMongo.example
Foi realizado a implementação das classes que representam o banco de dados de acordo com o diagrama logico.
=> 22 feature representação do banco de dados

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoEmpresaBasicDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoTitulacaoDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/empresa/EmpresaBasicDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/setoratuacao/SetorAtuacaoDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/usuario/UsuarioAuthDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/ContribuicaoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/CotaModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/DepoimentoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoEmpresaModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/EgressoTitulacaoModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/TipoBolsaModel.java
=> feat: atualização dos DTOs

frontend/src/components/CustomInput.vue, frontend/src/components/HeaderAndFooter.vue, frontend/src/pages/CadastroAdmin.vue, frontend/src/pages/CadastroPerfil.vue, frontend/src/router/index.ts, frontend/src/services/api.ts, frontend/src/services/localStorage.ts, frontend/src/store/CadastroPerfilStore.ts, frontend/src/store/LoginStore.ts, frontend/src/tests/LoginPage.test.ts, frontend/src/tests/ProfilePage.test.ts
Todas as mudanças foram realizadas com êxito.
=> [FEATURE]: Sistema de login e logout e validação dos inputs

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/auth/AuthenticationController.java, frontend/index.html, frontend/src/pages/CadastroEgresso.vue, frontend/src/pages/PageNotFound.vue, frontend/src/router/index.ts, frontend/src/router/routes.ts, frontend/src/store/CadastroEgresso.ts, frontend/src/store/LoginStore.ts
=> 165 bug pular cadastro após pré cadastro

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/curso/CursoDTO.java, backend/meuegresso/src/test/java/labes/facomp/ufpa/br/meuegresso/controller/anuncio/AnuncioControllerTest.java
refactor: remoção de import unused
=> fix: adição dos construtor a classe DTO

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/administrador/dashboard/DashAdmController.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/repository/usuario/UsuarioRepository.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/usuario/UsuarioService.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/usuario/impl/UsuarioServiceImpl.java, frontend/src/store/AnuncioVagaStore.ts, frontend/src/store/PainelStore.ts
A lista de egressos na página de egressos agora retorna os egressos cadastrados mais recentes, ou seja, em ordem descendente da data de cadastro.
=> fix: lista de egressos na página de registro de egresso em ordem descendente

frontend/src/pages/CadastroEgresso/CadastroEgresso.vue, frontend/src/pages/PaginaLogin/PaginaLogin.vue, frontend/src/pages/PerfilEgresso/PerfilEgresso.vue
=> fix: regex nova linkedin

frontend/src/components/PageSelector.vue, frontend/src/pages/PerfilEgresso/PerfilEgresso.vue
Quando haviam muitas páginas, a numeração de páginas mostradas estavam desordenadas. A função sort foi refatorada para obter o resultado esperado.
=> fix: numeração de páginas na ordem correta quando são muitas páginas

frontend/src/components/CustomCheckbox.vue, frontend/src/pages/CadastroEgresso/CadastroEgresso.vue
=> fix: asterisco vermelho em checkbox não obrigatória

frontend/src/pages/CadastroEgresso/components/FotoInput.vue
=> fix: limita texto no upload de arquivo e resetValidation

frontend/src/pages/CadastroAdmin/CadastroAdmin.vue, frontend/src/pages/CadastroAnuncio/CadastroAnuncio.vue, frontend/src/pages/CadastroEgresso/CadastroEgresso.vue, frontend/src/pages/CadastroPerfil/CadastroPerfil.vue, frontend/src/pages/EdicaoContaAdmin/EdicaoContaAdmin.vue, frontend/src/pages/EdicaoContaEgresso/EdicaoContaEgresso.vue, frontend/src/pages/EmailAdmin/EmailAdmin.vue, frontend/src/pages/NotificacoesAdmin/NotificacoesAdmin.vue, frontend/src/pages/PaginaLogin/PaginaLogin.vue, frontend/src/pages/PerfilEgresso/PerfilEgresso.vue, frontend/src/pages/RedefinirSenha/RedefinirSenha.vue
=> 348 melhoria inserir número máximo de caracteres nos inputs

frontend/src/components/AdminOptionsDropdown.vue, frontend/src/components/HeaderAndFooter.vue, frontend/src/components/NavbarDrawer.vue, frontend/src/components/UserDropdownMenu.vue, frontend/src/pages/HomePage/components/SociodemographicMap.vue, frontend/src/pages/PainelAdmin/PainelAdmin.vue, frontend/src/tests/AdminOptionsDropdown.test.ts, frontend/src/tests/UserDropdownMenu.test.ts
Refatoração geral de menus e dropdowns do sistema.
=> refact: menu lateral para mobile e refatoração do menu dropdown

frontend/src/components/AdminOptionsDropdown.vue, frontend/src/components/CustomDatepicker.vue, frontend/src/pages/CadastroEgresso/CadastroEgresso.vue, frontend/src/pages/CadastroEgresso/components/FotoInput.vue, frontend/src/pages/EmailAdmin/EmailAdmin.vue, frontend/src/pages/PainelAdmin/PainelAdmin.vue, frontend/src/router/routes.ts, frontend/src/store/CadastroEgresso.ts
=> feat: edição de egressos em qualquer status

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/publico/egresso/EgressoEmpresaBasicDTO.java
=> fix: endereço

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/administrador/egresso/EgressoAdmController.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/publico/egresso/EgressoPubController.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/publico/mapa/MapaController.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/repository/egresso/EgressoEmpresaRepository.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/repository/egresso/EgressoRepository.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/egresso/EgressoEmpresaService.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/egresso/EgressoService.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/egresso/impl/EgressoEmpresaServiceImpl.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/egresso/impl/EgressoServiceImpl.java, backend/meuegresso/src/test/java/labes/facomp/ufpa/br/meuegresso/controller/publico/egresso/EgressoPubControllerTest.java
=> 423 refactor melhorar lógica do fluxo do status de cadastro

frontend/src/pages/CadastroPerfil/CadastroPerfil.vue, frontend/src/pages/PoliticaPrivacidade/PoliticaPrivacidade.vue, frontend/src/router/routes.ts
=> feat: política de privacidade

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/adviser/ControllerAdvise.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/egresso/impl/EgressoServiceImpl.java
#453  bug consertado no front, pull request é para passar para a develop o commit de doc
=> [BUG] Erros em inglês estão sendo exibidos na tela do usuário

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/administrador/usuario/UsuarioAdmController.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/model/UsuarioModel.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/egresso/EgressoService.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/service/egresso/impl/EgressoServiceImpl.java, frontend/src/components/AdminOptionsDropdown.vue, frontend/src/store/PainelStore.ts
=> 469 feature delete usando usuario model

frontend/src/components/CustomInput.vue, frontend/src/pages/CadastroPerfil/CadastroPerfil.vue, frontend/src/pages/PoliticaPrivacidade/PoliticaPrivacidade.vue
=> feat: política de cookies

frontend/src/components/CustomSelect.vue, frontend/src/components/LocalizacaoSelect.vue
=> fix: opções não aparecem

backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/controller/egresso/EgressoController.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/administradores/egresso/EgressoAttDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/administradores/egresso/EgressoDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoCadastroDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoDTO.java, backend/meuegresso/src/main/java/labes/facomp/ufpa/br/meuegresso/dto/egresso/EgressoPublicDTO.java
=> fix: alterar regex do linkedin
